// hello_agent: end-to-end demo of pi-agent-go against the Anthropic API.
// Demonstrates:
//   - Constructing a Typed[I, O] tool with schema derived from a Go struct.
//   - Running the agent loop with streaming output.
//   - Hooks (BeforeToolCall logs every call).
//
// Usage:
//
//	export ANTHROPIC_API_KEY=...
//	go run ./examples/hello_agent
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"time"

	llm "github.com/amittimalsina/pi-llm-go"
	"github.com/amittimalsina/pi-llm-go/providers/anthropic"
	agent "github.com/amittimalsina/pi-agent-go"
)

// TimeArgs is the input schema for the get_current_time tool.
// jsonschema struct tags drive the JSON Schema generated by Typed.
type TimeArgs struct {
	Timezone string `json:"timezone,omitempty" jsonschema:"description=IANA timezone (e.g. 'America/New_York'). Defaults to UTC if omitted."`
}

// TimeResult is what the tool returns; we serialize as JSON so the model
// gets a structured payload it can reason about.
type TimeResult struct {
	Timezone string `json:"timezone"`
	ISO8601  string `json:"iso8601"`
}

func main() {
	apiKey := os.Getenv("ANTHROPIC_API_KEY")
	if apiKey == "" {
		fmt.Fprintln(os.Stderr, "ANTHROPIC_API_KEY is required")
		os.Exit(2)
	}

	provider, err := anthropic.New(anthropic.Options{APIKey: apiKey})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	timeTool := agent.Typed[TimeArgs, TimeResult](
		"get_current_time",
		"Get the current wall-clock time as ISO-8601 in an IANA timezone.",
		func(ctx context.Context, in TimeArgs) (TimeResult, error) {
			tz := in.Timezone
			if tz == "" {
				tz = "UTC"
			}
			loc, err := time.LoadLocation(tz)
			if err != nil {
				return TimeResult{}, fmt.Errorf("unknown timezone %q: %w", tz, err)
			}
			return TimeResult{
				Timezone: tz,
				ISO8601:  time.Now().In(loc).Format(time.RFC3339),
			}, nil
		},
		func(r TimeResult) string {
			b, _ := json.Marshal(r)
			return string(b)
		},
	)

	a, err := agent.New(agent.Config{
		LLM:          provider,
		Model:        anthropic.ClaudeSonnet4_6,
		SystemPrompt: "You are a helpful assistant. Use tools when needed.",
		Tools:        []agent.AgentTool{timeTool},
		MaxTokens:    1024,
		BeforeToolCall: func(ctx context.Context, rc agent.RunContext, call agent.ToolCallInfo) (bool, string, error) {
			fmt.Fprintf(os.Stderr, "[iter %d] calling %s(%s)\n", rc.Iteration, call.Name, string(call.Arguments))
			return false, "", nil
		},
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	prompt := "What time is it right now in Tokyo and New York?"
	if len(os.Args) > 1 {
		prompt = os.Args[1]
	}

	for event, err := range a.Run(context.Background(), prompt) {
		if err != nil {
			fmt.Fprintln(os.Stderr, "\nerror:", err)
			os.Exit(1)
		}
		switch e := event.(type) {
		case agent.EventLLMStream:
			if d, ok := e.Event.(llm.EventTextDelta); ok {
				fmt.Print(d.Delta)
			}
		case agent.EventToolEnd:
			fmt.Fprintf(os.Stderr, "[%s -> %s]\n", e.Name, e.Result)
		case agent.EventRunEnd:
			fmt.Fprintf(os.Stderr, "\n[done in %d iterations]\n", e.Iterations)
		}
	}
}
